on: push
name: CI
jobs:
  build:
    strategy:
      matrix:
        go-version: [dev-latest, mod]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}

      - name: Prepare Embed
        run: |
          mkdir -p ui/dist
          touch ui/dist/index.html
      - name: Build
        run: go build main.go
