on: push
name: CI
jobs:
  go:
    strategy:
      matrix:
        go-version: [dev-latest, mod]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}

      - name: Prepare Embed
        run: |
          mkdir -p ui/dist
          touch ui/dist/index.html
      - name: Build
        run: go build main.go
      - name: Test
        run: go test -race -v ./... -count=1
