on: push
name: CI
jobs:
  build:
    strategy:
      matrix:
        node-versions: [20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: npm install
        working-directory: ui
        run: npm install

      - name: Lint
        working-directory: ui
        run: npm run lint

      - name: Build
        working-directory: ui
        run: npm run build
