on:
  pull_request:
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - '**/*.yaml'
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [dev-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2.2
        with:
          version: ${{ matrix.go-version }}
      - name: Prepare Embed
        run: |
          mkdir -p ui/dist
          touch ui/dist/index.html
      - name: Test
        run: go test -race -v ./... -count=1
